### ISSUE TITLE
[Meta] Next

### ISSUE THREAD

**Issue by hadim** [datamol-io/graphium#57]
@DomInvivo @Therence1 here is what I have in mind for the release:

- [x] Finish current PRs (dom)
- [x] Logic to load a pretrained model (hadrien, dom)
- [x] Create a public S3 bucket and put in it two folders: `pretrained-models` and `datasets`. (hadrien)
- [x] Move `micro_ZINC` and `ZINC_bench_gnn` into the S3 bucket + add a CLI tools for easy download: `goli download micro_ZINC /my/path`. (hadrien)
- [x] Restructure README: add plenty of fancy icons. (hadrien)
- [x] Better doc: make the index doc page (what is goli, what you can do with it, etc) (hadrien)
- [x] Rework tutorials: keep the code as it is but add a more detailed description of what is happening (eventually add relevant equations + images). (hadrien and dom)
- [x] Find a logo (hadrien, therence, dom)
- [ ] Draft a blog post (dom want to give it a try?)
